from __future__ import annotations
from abc import ABC
import inspect
from dataclasses import astuple, dataclass, field
import struct
import typing
from typing import Union
import zlib

from fprime_gds.common.fpy.error import BackendError

from fprime_gds.common.fpy.bytecode.directives import (
    Directive,
)

from fprime.common.models.serialize.type_base import BaseType as FppValue

from fprime_gds.common.fpy.syntax import Ast
from fprime_gds.common.fpy.util import is_instance_compat

MAX_DIRECTIVES_COUNT = 1024
MAX_DIRECTIVE_SIZE = 2048
MAX_STACK_SIZE = 1024

COMPILER_MAX_STRING_SIZE = 128


# a value of type FppType is a Python `type` object representing
# the type of an Fprime value
FppType = type[FppValue]


@dataclass
class Ir:
    id: int = field(init=False, repr=False, default=None)

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, value):
        if not isinstance(value, Ir):
            return False
        assert self.id is not None
        return self.id == value.id


@dataclass
class IrStmt(Ir):
    pass


@dataclass
class IrInstruction(IrStmt):
    # instruction generates strictly one directive
    pass


@dataclass
class IrDirective(IrInstruction):
    dir: Directive


@dataclass
class IrGoto(IrInstruction):
    label: typing.Union[str, "IrBasicBlock"]


@dataclass
class IrFallthrough(IrInstruction):
    pass


# TODO consider making this have two args, one which is the true case, one which is false
@dataclass
class IrIf(IrInstruction):
    true_case: IrBasicBlock
    false_case: IrBasicBlock


@dataclass
class IrBasicBlock:
    node: Ast
    name: str
    predecessors: list["IrBasicBlock"] = field(default_factory=list)
    successors: list["IrBasicBlock"] = field(default_factory=list)
    stmts: list[Union[IrStmt, Directive]] = field(default_factory=list)


@dataclass
class IrFunction:
    args: dict[str, FppType]
    return_type: FppType
    blocks: list[IrBasicBlock] = field(default_factory=list)
    # entry is first block


@dataclass
class IrModule:
    funcs: list[IrFunction]


class IrVisitor:

    def _find_custom_visit_func(self, stmt: IrStmt):
        for name, func in inspect.getmembers(type(self), inspect.isfunction):
            if not name.startswith("visit"):
                # not a visitor
                continue
            signature = inspect.signature(func)
            params = list(signature.parameters.values())
            assert len(params) == 6
            assert params[1].annotation is not None
            annotations = typing.get_type_hints(func)
            param_type = annotations[params[1].name]
            if is_instance_compat(stmt, param_type):
                return getattr(self, name)
        return self.visit_stmt_default

    def _visit_stmt(
        self,
        stmt: IrStmt,
        block: IrBasicBlock,
        func: IrFunction,
        mod: IrModule,
        state: BackendState,
    ):
        visit_func = self._find_custom_visit_func(stmt)
        visit_func(stmt, block, func, mod, state)

    def visit_stmt_default(
        self,
        stmt: IrStmt,
        block: IrBasicBlock,
        func: IrFunction,
        mod: IrModule,
        state: BackendState,
    ):
        pass

    def visit_basic_block(
        self, block: IrBasicBlock, func: IrFunction, mod: IrModule, state: BackendState
    ):
        pass

    def visit_function(self, func: IrFunction, mod: IrModule, state: BackendState):
        pass

    def visit_module(self, mod: IrModule, state: BackendState):
        pass

    def run(self, mod: IrModule, state: BackendState):
        """runs the visitor, starting at the module, descending depth-first"""

        for func in mod.funcs:
            for block in func.blocks:
                for stmt in block.stmts:
                    self._visit_stmt(stmt, block, func, mod, state)
                    if len(state.errors) != 0:
                        return
                self.visit_basic_block(block, func, mod, state)
                if len(state.errors) != 0:
                    return
            self.visit_function(func, mod, state)
            if len(state.errors) != 0:
                return

        self.visit_module(mod, state)
        if len(state.errors) != 0:
            return


@dataclass
class BackendState:
    """a collection of input, internal and output state variables and maps"""

    block_dirs: dict[IrBasicBlock, list[Directive]] = field(default_factory=dict)
    func_dirs: dict[IrFunction, list[Directive]] = field(default_factory=dict)
    mod_dirs: dict[IrModule, list[Directive]] = field(default_factory=dict)
    dir_line_indices: dict[IrInst, int] = field(default_factory=dict)

    goto_indices: dict[Union[IrIf, IrGoto], int] = field(default_factory=dict)

    func_goto_labels: dict[IrFunction, dict[str, int]] = field(default_factory=dict)

    errors: list[BackendError] = field(default_factory=list)
    """a list of all compile exceptions generated by passes"""

    def err(self, msg):
        """adds an exception to internal state"""
        self.errors.append(BackendError(msg))


SCHEMA_VERSION = 2

HEADER_FORMAT = "!BBBBBHI"
HEADER_SIZE = struct.calcsize(HEADER_FORMAT)


@dataclass
class Header:
    majorVersion: int
    minorVersion: int
    patchVersion: int
    schemaVersion: int
    argumentCount: int
    statementCount: int
    bodySize: int


FOOTER_FORMAT = "!I"
FOOTER_SIZE = struct.calcsize(FOOTER_FORMAT)


@dataclass
class Footer:
    crc: int


def deserialize_directives(bytes: bytes) -> list[Directive]:
    header = Header(*struct.unpack_from(HEADER_FORMAT, bytes))

    if header.schemaVersion != SCHEMA_VERSION:
        raise RuntimeError(
            f"Schema version wrong (expected {SCHEMA_VERSION} found {header.schemaVersion})"
        )

    dirs = []
    idx = 0
    offset = HEADER_SIZE
    while idx < header.statementCount:
        offset_and_dir = Directive.deserialize(bytes, offset)
        if offset_and_dir is None:
            raise RuntimeError("Unable to deserialize sequence")
        offset, dir = offset_and_dir
        dirs.append(dir)
        idx += 1

    if offset != len(bytes) - FOOTER_SIZE:
        raise RuntimeError(
            f"{len(bytes) - FOOTER_SIZE - offset} extra bytes at end of sequence"
        )

    return dirs


def serialize_directives(dirs: list[Directive]) -> tuple[bytes, int]:
    output_bytes = bytes()

    for dir in dirs:
        dir_bytes = dir.serialize()
        if len(dir_bytes) > MAX_DIRECTIVE_SIZE:
            print(
                BackendError(
                    f"Directive {dir} in sequence too large (expected less than {MAX_DIRECTIVE_SIZE}, was {len(dir_bytes)})"
                )
            )
            exit(1)
        output_bytes += dir_bytes

    header = Header(0, 0, 0, SCHEMA_VERSION, 0, len(dirs), len(output_bytes))
    output_bytes = struct.pack(HEADER_FORMAT, *astuple(header)) + output_bytes

    crc = zlib.crc32(output_bytes) % (1 << 32)
    footer = Footer(crc)
    output_bytes += struct.pack(FOOTER_FORMAT, *astuple(footer))

    return output_bytes, crc
